import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/redux/store/provider";
import "./globals.css";
import { Toaster } from "sonner";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="preload" href="/_next/static/css/app.css" as="style" />
<meta name="theme-color" content="#ffffff" />
      <body
        className="antialiased"
      >
        <Providers>
          {children}
           <Toaster 
            position="top-right" 
            richColors 
            closeButton 
            duration={4000} 
          />
        </Providers>
      
      </body>
    </html>
  );
}
